### ISSUE TITLE
Bug in plot_data_full.Rmd

### ISSUE THREAD

**Issue by sylvainschmitt** [EmiDt/symphostage#8]
Following bug:
> Error in overscope_eval_next(overscope, expr) : objet 'morphotype_field' introuvable

Line 45-48:
```
Trait_mean_individuals_vect<- Traits_brut_data %>% 
  dplyr::select(n_parcelle, n_carre, n_arbre, morphotype, Dawkins, diameter, Xutm, Yutm, wood_presence, morphotype_field) %>% 
  group_by(n_parcelle, n_carre, n_arbre, morphotype, Dawkins, diameter, wood_presence, morphotype_field) %>%
    summarize()
```

**Comment by EmiDt** [comment]
May be you don"t have the last version of trait brut data , I changed it to add morphotype_filed column

**Comment by sylvainschmitt** [comment]
Ok so I suppose it is okay now and I am closing the issue (I will test only tomorrow)
